version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: weather
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: always

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
#  app:
  #    build: .
#    ports:
#      - "9000:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db/tc
#      SPRING_DATASOURCE_USERNAME: tc
#      SPRING_DATASOURCE_PASSWORD: tc
#    depends_on:
#      - db2

#version: '3'
  #
  #services:
  #  app:
  #    image: 'docker-spring-boot-postgres:latest'
  #    build:
  #      context: .
  #    container_name: app
  #    depends_on:
  #      - db1
  #    environment:
  #      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
  #      - SPRING_DATASOURCE_USERNAME=compose-postgres
  #      - SPRING_DATASOURCE_PASSWORD=compose-postgres
  #      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  #
  #  db1:
  #    image: 'postgres:13.1-alpine'
  #    container_name: db2
  #    environment:
  #      - POSTGRES_USER=compose-postgres
  #      - POSTGRES_PASSWORD=compose-postgres